title: Welcome to Setwork Necurity
description: Powered by Jekyll on GitHub Pages
url: "https://pbmundas.github.io"
baseurl: "/blog" # Use this if you want the blog at https://pbmundas.github.io/blog
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true
