title: Welcome to Setwork Necurity
description: Powered by Jekyll on GitHub Pages
url: "https://pbmundas.github.io"
baseurl: "/blog" # Ensures site is served at /blog subdirectory
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true
permalink: /:year/:month/:day/:title.html # Optional: Clean URL structure
